### ISSUE TITLE
Update dependencies?

### ISSUE THREAD

**Issue by shuwens** [jfloff/pivot-tracing-docker#1]
Hello, 
It seems to be very handy to play with pivot tracing and other stuff. But the `protobuf` part needs to be updated. Also, the `aclocal` seems to be annoying, I noticed that on my system(Arch Linux) it is aclocal-1.15 and on Ubuntu16 it is acloacl-1.11

**Comment by jfloff** [comment]
Thank you for the comment.

Regarding `protobuf` according to Pivot Tracing's [documentation](http://brownsys.github.io/tracing-framework/docs/tutorials/prerequisites.html) it only supports version 2.5. iirc when I was building I had issues with newer versions, but you are free to try updating and see results.

Regarding `aclocal` I'm not installing that dependency directly, so I'm just letting apt-get deal with that. 

Was there any reason why you wanted updated dependencies? Any problem using the container?

**Comment by shuwens** [comment]
I see. It is just that the `aclocal` is kinda making it not working out of box, which is pretty upset. 

Looks like there is sth wrong with the `protobuf` anyway.

```
-> % file protobuf-2.5.0.tar.gz 
protobuf-2.5.0.tar.gz: HTML document, UTF-8 Unicode text, with very long lines
```

These are the two bugs I have met so far.

**Comment by jfloff** [comment]
But are having trouble building the docker image? Could you show the full output?

**Comment by shuwens** [comment]
```
-> % docker build --rm=true -t jfloff/pivot-tracing .

Sending build context to Docker daemon 6.144 kB
Step 1 : FROM java:7
 ---> 96da005cd161
Step 2 : MAINTAINER João loff <jfloff@gsd.inesc-id.com>
 ---> Using cache
 ---> 8d8a734d37ed
Step 3 : RUN apt-get update && apt-get install -y --no-install-recommends       build-essential       curl       maven       aspectj       ant   && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 44a5f1c45dc8
Step 4 : RUN mkdir /home/protobuf && cd /home/protobuf   && curl -# -O https://protobuf.googlecode.com/files/protobuf-2.5.0.tar.gz   && gunzip protobuf-2.5.0.tar.gz   && tar -xvf protobuf-2.5.0.tar   && cd protobuf-2.5.0   && ./configure --prefix=/usr   && make && make install   && rm -rf /home/protobuf
 ---> Running in b8e3ef59c209
######################################################################## 100.0%

gzip: protobuf-2.5.0.tar.gz: not in gzip format
The command '/bin/sh -c mkdir /home/protobuf && cd /home/protobuf   && curl -# -O https://protobuf.googlecode.com/files/protobuf-2.5.0.tar.gz   && gunzip protobuf-2.5.0.tar.gz   && tar -xvf protobuf-2.5.0.tar   && cd protobuf-2.5.0   && ./configure --prefix=/usr   && make && make install   && rm -rf /home/protobuf' returned a non-zero code: 1
```

Like I said, the protobuf pkg seems not working.

**Comment by jfloff** [comment]
I've found the issue. The link for the `protobuf` download was pointing towards the closed googlecode.com repository. Since Google Code has closed, and all repositories merged to Github I had to change the URL for the new github repo. 

Thank you for finding this out! Please confirm that you can now build the image.

**Comment by jfloff** [comment]
I guess that fixed it. Closing this issue. 

Once again thank you for the report!
